import type { AppProps } from 'next/app';
import Head from 'next/head';
import Link from 'next/link';

import { QueryClientProvider, QueryClient } from '@tanstack/react-query';
import { ReactQueryDevtools } from '@tanstack/react-query-devtools';

import { Provider } from 'react-redux';
import { store } from '../lib/redux/store';

import "../styles/globals.css";

const queryClient = new QueryClient();

export default function App({ Component, pageProps }: AppProps) {
  return (
    <Provider store={store}>
      <QueryClientProvider client={queryClient}>
        <Head>
          <title>TanStack Query Project</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div id="app-wrapper">
          <header>
            <nav>
              <Link href="/">
                Home
              </Link>
              <Link href="/superheros">
                Superheros
              </Link>
            </nav>
          </header>
          <main>
            <Component {...pageProps} />
          </main>
        </div>
        {process.env.NODE_ENV === 'development' &&
          <ReactQueryDevtools
            initialIsOpen={false}
            position="bottom-left"
          />}
      </QueryClientProvider>
    </Provider>
  );
};
